<a href="https://colab.research.google.com/github/gitzV/DataScience/blob/main/tds_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt

In [5]:
a1 = np.array([1,2,3,4])
a1.shape


(4,)

In [6]:
a2 = np.array([[1,2,3,4]]) # initialized with a numpy list 
a2.shape

(1, 4)

In [7]:
a3 = np.array([[1], 
               [2], 
               [3], 
               [4]])
a3.shape

(4, 1)

In [9]:
M1 = np.array([[1,0,0], 
               [0,1,0], 
               [0,0,1], 
               [0,0,1]])
M1 
M1.shape


(4, 3)

In [10]:
m = M1.shape[0] # number of rows
n = M1.shape[1] # number of columns 
print("m: {}  n:{}".format(m,n))

m: 4  n:3


In [11]:
M2 = np.reshape(M1, (1,12))
display(M2)
print(M2.shape)

array([[1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1]])

(1, 12)


In [13]:
print("original a2.shape: ", a1.shape) 

# reshape into a vector
a1_vec = np.reshape(a1, (a1.shape[0],1))

print("reshaped: ", a1_vec.shape)

original a2.shape:  (4,)
reshaped:  (4, 1)


In [14]:
# python list: 
l = [1,2,3,4] 

# np.array 
l_np = np.array(l)

# different print style 
print(l) 
print(l_np) # note the lack of commas 

[1, 2, 3, 4]
[1 2 3 4]


In [15]:
print(l*5) # multiplying a python list replicates it
print(l_np*5) # numpy applies operation elemntwise

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]
[ 5 10 15 20]


In [18]:
M3 = np.random.randn(5,5)
M3 

array([[ 0.30567421,  0.92986093,  1.22559032,  0.04743279, -2.79782543],
       [-0.15016506, -0.92088147, -1.59947316,  1.89481548, -0.2807835 ],
       [ 0.24759927, -0.09072047,  0.75112313, -0.60664418, -1.5336063 ],
       [-1.13856817,  0.97913584, -0.40704266,  0.76651127,  1.44291134],
       [ 0.79251604,  1.15151535,  1.06823261,  0.32276066, -0.354841  ]])

In [19]:
n = 10
theta = np.random.randn(n,1) 
theta

array([[ 0.03799748],
       [-1.24781041],
       [ 0.37703551],
       [-0.86374244],
       [-0.37825835],
       [ 0.58778976],
       [-1.48786568],
       [-1.43772297],
       [ 0.88494751],
       [ 0.31181532]])